### ISSUE TITLE
BBCode output is only a line

### ISSUE THREAD

**Issue by 995qa** [jmxamongusmodder/Pixel-art-BRANCHES#1]
When I made both a 16x16 and an 8x8 image into BBCode, both outputs show as a line in the bio and in-game.

**Comment by chicken-nugget1104** [comment]
> When I made both a 16x16 and an 8x8 image into BBCode, both outputs show as a line in the bio and in-game.

Yea i saw this issue too, didnt happen before.

Gonna look into it!

**Comment by chicken-nugget1104** [comment]
> > When I made both a 16x16 and an 8x8 image into BBCode, both outputs show as a line in the bio and in-game.
> 
> Yea i saw this issue too, didnt happen before.
> 
> Gonna look into it!

Try using the newest published build @995qa
